### ISSUE TITLE
Non-contiguous discrete spaces

### ISSUE THREAD

**Issue by jbrea** [JuliaReinforcementLearning/ReinforcementLearningBase.jl#2]
Currently we have in Atari non-contiguous discrete spaces, e.g.
```julia
julia> using ReinforcementLearningEnvironmentAtari
julia> env = AtariEnv("breakout");
julia> env.actions
4-element Array{Int32,1}:
 0
 1
 3
 4
```
Should we support them here as a variant of a DiscreteSpace?

**Comment by findmyway** [comment]
I think we can keep the `DiscreteSpace` as it is and let the environment to interprete the element in that Space.

For example, in the Atari Environment, we can have another field named `actionspace`.
```
env.actionspace = DiscreteSpace(length(env.actions), 1)  # index starts with 1
a = sample(env.actionspace)
interact!(env, a) = begin
    r = act(env.ale, env.actions[a])
    ...
    # something else
end
```

On the other hand, in the ViZDoom environment, we'd need to inerprete the discrete action as an one-hot vector.

**Comment by jbrea** [comment]
OK, thanks.
