### ISSUE TITLE
Observe, observation, state

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearningBase.jl#45]
I am getting a bit mislead so a guess other ones could be mislead as well by something:

I feel that the term "observation" is used in two specific ways: 
- the first is the result of the observe function (according to the documentation https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/master/src/interface.jl#L255 ) and corresponds to something like (reward = env.done ? zero(T) : one(T), terminal = env.done, state = env.state). This was picked here: https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/classic_control/cartpole.jl#L99. And it seems that the output of "observe" in all the envs of ReinforcementLearningEnvironements.jl are a tuple like that.
- the second is the "observation" of observation_space, which correspond to the part of the state space that can be observed by the player. 

Now let's go to the point: Am I right ? 
If I am, I find this a bit misleading and think that we could maybe discuss a potentiel change of the terms used. 

What do you think about this ?

**Comment by findmyway** [comment]
> Now let's go to the point: Am I right ?

Yeah, you are exactly right here.

We'd better rename `get_observation_space` to `get_state_space` later.

**Comment by felixchalumeau** [comment]
Ok ! Let me know if you are taking care of this change or if you want me to do it !

**Comment by findmyway** [comment]
Considering that it has been used across different packages, I'll mark it as deprecated first.
